**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



Creation of ndarray

Write python code to create 3d array in different ways with 15 elements.
Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
Find all attributes of array1 and array2
Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [1]:
import numpy as np

In [7]:
a=np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
a

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [9]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin=3)
b

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [16]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [12]:
b.reshape(1,3,5)


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [13]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
array1 = np.random.rand(20).reshape(1,4,5)
array1

array([[[0.21043129, 0.08536429, 0.8152328 , 0.0853012 , 0.17495314],
        [0.77683683, 0.27217932, 0.25766967, 0.84520632, 0.41385565],
        [0.56480284, 0.94692332, 0.20157883, 0.92637762, 0.6898488 ],
        [0.75022202, 0.35347187, 0.42620667, 0.52424676, 0.07395098]]])

attributes

In [17]:
arr1


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [18]:
arr1.ndim

4

In [19]:
arr1.size

12

In [20]:
arr1.itemsize

4

In [21]:
arr1.nbytes

48

In [23]:
arr1.dtype

dtype('int32')

stat

In [24]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [26]:
arr1.mean()

6.5

In [27]:
np.median(arr1)

6.5

In [28]:
arr1.var()

11.916666666666666

In [29]:
arr1.std()

3.452052529534663

In [31]:
range = arr1.max()-arr1.min()
range

11

In [33]:
q1 = np.percentile(arr1,25)
q1

3.75

In [34]:
q3 = np.percentile(arr1,75)
q3

9.25

In [35]:
IQR=q3-q1
IQR

5.5

In [36]:
lower = q1 - (1.5*IQR)
upper = q3 + (1.5*IQR)


In [39]:
upper

17.5

In [38]:
lower

-4.5

In [41]:
arr1[arr1>upper]


array([], dtype=int32)

In [42]:
arr1[arr1<lower]


array([], dtype=int32)

Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [43]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [46]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr1[3]

73

In [48]:
arr2[2][1]


7

In [49]:
arr1[:5]


array([ 0, 11, 26, 73, 42])

In [55]:
arr2[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [56]:
arr1[1:8]


array([11, 26, 73, 42, 51,  6, 77])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.


In [58]:
n = np.array([1, 2, 3, 4, 5],dtype = "int16")
n

array([1, 2, 3, 4, 5], dtype=int16)

In [60]:
n.dtype

dtype('int16')

In [62]:
n = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "float64")
n


array([0.1, 0.2, 0.3, 0.4, 0.5])

In [63]:
n.dtype


dtype('float64')

In [66]:
num = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
num.dtype

dtype('int32')

In [67]:
num = np.array([1, 2, 3, 4, 5],dtype = "float32")
num

array([1., 2., 3., 4., 5.], dtype=float32)


**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.

In [68]:
n = np.random.randint(0,101,10)
n

array([ 0, 24, 43, 97, 28, 78, 71,  4, 52, 77])

In [69]:
np.random.uniform(-1,1,5)


array([ 0.5294463 , -0.70334123,  0.68141253,  0.00602129, -0.88829337])

In [70]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[55, 76, 95, 55],
       [64, 77, 92, 98],
       [75, 66, 59, 73],
       [56, 99, 54, 72]])

stat

In [71]:
rand_matrix.mean()
rand_matrix

array([[55, 76, 95, 55],
       [64, 77, 92, 98],
       [75, 66, 59, 73],
       [56, 99, 54, 72]])

In [72]:
np.median(rand_matrix)


72.5

In [73]:
rand_matrix.max()-rand_matrix.min()  


45

In [74]:
rand_matrix.std()


15.410528057143273

In [75]:
rand_matrix.var()
rand_matrix

array([[55, 76, 95, 55],
       [64, 77, 92, 98],
       [75, 66, 59, 73],
       [56, 99, 54, 72]])

In [76]:
q1 = np.percentile(rand_matrix,25)

q3 = np.percentile(rand_matrix,75)


In [77]:
IQR = q3-q1


In [78]:
lower = q1 - (1.5 * IQR)
upper = q3 + (1.5 * IQR)
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [79]:
rand_matrix[rand_matrix > upper]


array([], dtype=int32)

**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?


In [80]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])


In [81]:
salaries[salaries < 50000]


array([31250, 39828, 41671, 34225, 32199])

Normal distribution

In [82]:
np.median(salaries)


61699.5

In [83]:
salaries.max() - salaries.min()   


3082388

In [85]:
avg = salaries.mean()
q1 = np.percentile(salaries,25)
q3 = np.percentile(salaries,75)
avg


166169.16666666666

In [86]:
q3



84496.5

In [87]:
salaries[(salaries<avg) & (salaries >= q3)]


array([87877, 85051, 94868, 98446, 99658, 89224, 90947])

In [88]:
q1

52963.25

In [96]:
np.sum(salaries < q1)


8