### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

***Data Cleaning using numpy***
The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

Find the no of outliers and missing values?
replace the outliers with 45 and missing value with 87.
what is the average marks of students after 2nd step?
How many students got less than 60 marks?
what is the maximum marks?
Convert the marks to float32.

In [3]:
import numpy as np

In [26]:
marks=np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53,40])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  40.])

In [27]:
np.sum(np.isnan(marks))        ##there are 4missing values

4

In [28]:
outliers=(marks<0) | (marks>100)
np.sum(outliers)##these are  no.of outliers

3

In [29]:
marks=(np.where(np.isnan(marks),87,marks).astype('int16'))
marks

array([ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
        87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
         2,  53,  40], dtype=int16)

In [30]:
marks=(np.where(outliers,45,marks).astype('int16'))
marks


array([44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56, 81,
       59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 40], dtype=int16)

In [31]:
average_marks=np.mean(marks)

In [32]:
average_marks

56.827586206896555

In [33]:
less_60=np.sum(marks<60)

In [34]:
less_60

18

In [35]:
max=np.max(marks)

In [36]:
max

97

In [37]:
marks.dtype

dtype('int16')

In [39]:
marks=marks.astype('float32')
marks.dtype

dtype('float32')

Solving Linear Equations
2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12

2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

Solve the system of equations using NumPy's linalg.solve function.

In [43]:
a=np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b=np.array([10,5,12])
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [46]:
c=np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
d=np.array([8,1,7,3])
np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [47]:
e=np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
f=np.array([10,-3,4])
np.linalg.solve(e,f)

array([2.85365854, 0.6097561 , 0.87804878])

Conditional Selection with np.where()
​
1.  Generate a random 1D array A of 10 integers between 1 and 100.
​
2.  Use np.where() to find the indices where the elements of A are greater than 50.
​
3.  Create a new array B that contains elements from A where the condition is met.
​
4.  Calculate the mean of array B and print it along with arrays A and B.

In [48]:
import random


In [49]:
A=np.random.randint(1,100,10)

In [50]:
A

array([93, 94, 71, 58, 80,  5, 56, 70, 14, 99])

In [54]:
c=A[np.where(A>50)]
c

array([93, 94, 71, 58, 80, 56, 70, 99])

In [56]:
B=c
B

array([93, 94, 71, 58, 80, 56, 70, 99])

In [58]:
print(np.mean(B))
print(A)
print(B)

77.625
[93 94 71 58 80  5 56 70 14 99]
[93 94 71 58 80 56 70 99]


Replace Values with np.where()

Create a 4x4 random integer matrix C with values between -10 and 10.

Use np.where() to replace all negative values in matrix C with 0.

Print the original matrix C and the modified matrix.

In [60]:
C=np.random.randint(-10,10,16).reshape(4,4)
C

array([[ 9, -9, -5, -5],
       [ 3, -6, -4,  9],
       [ 7, -4,  2, -9],
       [ 5,  4, -4, -2]])

In [61]:
c=np.where(C<0,0,C)
c


array([[9, 0, 0, 0],
       [3, 0, 0, 9],
       [7, 0, 2, 0],
       [5, 4, 0, 0]])

In [63]:
print(f"Original matrix\n {C} \n \n Modified matrix \n {c}")

Original matrix
 [[ 9 -9 -5 -5]
 [ 3 -6 -4  9]
 [ 7 -4  2 -9]
 [ 5  4 -4 -2]] 
 
 Modified matrix 
 [[9 0 0 0]
 [3 0 0 9]
 [7 0 2 0]
 [5 4 0 0]]
